
module.exports.getStr = function(val,key){
  var spaces = '  ';
  var str = "";
  str = "/* apifile */\n\n";
  str += "var messages = require('../../../config/messages');\n";
  str += "var swagger = require('swagger-node-express');\n";

  str += "\n/*get "+val+" by id */\n\n";
  str += "module.exports.get"+val+"ByIdSpec = {\n";
  str += spaces + "'spec': {\n";
  str += spaces+spaces + "'description': '"+val+"操作',\n";
  str += spaces+spaces + "'method': 'GET',\n";
  str += spaces+spaces + "'path': '/"+val+"/{id}',\n";
  str += spaces+spaces + "'summary': '通过ID获取"+val+"信息',\n";
  str += spaces+spaces + "'notes': '通过ID获取"+val+"信息, 返回一个JSON对象',\n";
  str += spaces+spaces + "'type': '"+val+"',\n";
  str += spaces+spaces + "'parameters': [swagger.pathParam('id', 'ID', 'INTEGER')],\n";
  str += spaces+spaces + "'responseMessages': [\n";
  str += spaces+spaces+spaces + " messages.OK_RESPONSE('"+val+"'),\n";
  str += spaces+spaces+spaces + " messages.InvalidIndentifier('"+key.description+"'),\n";
  str += spaces+spaces+spaces + " messages.NotFound('"+key.description+"')\n";
  str += spaces+spaces + "],\n";
  str += spaces+spaces + "'nickname': 'get"+val+"ById',\n";
  str += spaces + "}\n";
  str += "};\n";

  str += "\n/*create "+val+" */\n\n";
  str += "module.exports.create"+val+"Spec = {\n";
  str += spaces + "'spec': {\n";
  str += spaces+spaces + "'description': 'create "+val+"',\n";
  str += spaces+spaces + "'method': 'POST',\n";
  str += spaces+spaces + "'path': '/"+val+"',\n";
  str += spaces+spaces + "'summary': '创建一个"+val+"',\n";
  str += spaces+spaces + "'notes': '创建一个"+val+",请求和响应同时支持JSON数据格式,把下面的JSON复制到body参数中测试',\n";
  str += spaces+spaces + "'type': '"+val+"',\n";
  str += spaces+spaces + "'parameters': [{ \n";
  str += spaces+spaces+spaces + "'name':'body', \n";
  str += spaces+spaces+spaces + "'description':'Create a "+val+"', \n";
  str += spaces+spaces+spaces + "'required':true, \n";
  str += spaces+spaces+spaces + "'type':'"+val+"', \n";
  str += spaces+spaces+spaces + "'paramType':'body' \n";
  str += spaces+spaces + "}],\n";
  str += spaces+spaces + "'responseMessages': [\n";
  str += spaces+spaces+spaces + " messages.Created('"+val+"'),\n";
  str += spaces+spaces+spaces + " messages.Invalid('"+key.description+" message')\n";
  str += spaces+spaces + "],\n";
  str += spaces+spaces + "'nickname': 'create"+val+"',\n";
  str += spaces + "}\n";
  str += "};\n";

  str += "\n/*update "+val+" */\n\n";
  str += "module.exports.update"+val+"Spec = {\n";
  str += spaces + "'spec': {\n";
  str += spaces+spaces + "'description': 'update "+val+"',\n";
  str += spaces+spaces + "'method': 'PUT',\n";
  str += spaces+spaces + "'path': '/"+val+"/{id}',\n";
  str += spaces+spaces + "'summary': '更新"+val+"信息',\n";
  str += spaces+spaces + "'notes': 'ID为必须, 必须是一个大于0的整数, 请求和响应同时支持JSON和XML数据格式',\n";
  str += spaces+spaces + "'type': '"+val+"',\n";
  str += spaces+spaces + "'parameters': [swagger.pathParam('id', 'ID', 'INTEGER')],\n";
  str += spaces+spaces + "'responseMessages': [\n";
  str += spaces+spaces+spaces + " swagger.errors.invalid('id'),,\n";
  str += spaces+spaces+spaces + " swagger.errors.notFound('"+val+"')\n";
  str += spaces+spaces + "],\n";
  str += spaces+spaces + "'nickname': 'update"+val+"ById',\n";
  str += spaces + "}\n";
  str += "};\n";

  str += "\n/*delete "+val+" */\n\n";
  str += "module.exports.delete"+val+"Spec = {\n";
  str += spaces + "'spec': {\n";
  str += spaces+spaces + "'description': 'delete "+val+"',\n";
  str += spaces+spaces + "'method': 'DELETE',\n";
  str += spaces+spaces + "'path': '/"+val+"/{id}',\n";
  str += spaces+spaces + "'summary': '删除"+val+"信息',\n";
  str += spaces+spaces + "'notes': '删除"+val+"ID对应的记录, ID为必须, 必须是一个大于0的整数, 请求和响应同时支持JSON和XML数据格式',\n";
  str += spaces+spaces + "'type': '"+val+"',\n";
  str += spaces+spaces + "'parameters': [swagger.pathParam('id', 'ID', 'INTEGER')],\n";
  str += spaces+spaces + "'responseMessages': [\n";
  str += spaces+spaces+spaces + " swagger.errors.invalid('id'),,\n";
  str += spaces+spaces+spaces + " swagger.errors.notFound('"+val+"')\n";
  str += spaces+spaces + "],\n";
  str += spaces+spaces + "'nickname': 'delete"+val+"ById',\n";
  str += spaces + "}\n";
  str += "};\n";

  return str;
};
